### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by MystPhysX**
This should work. The change was not too drastic.

### CODE REVIEW

**Comment by equiteam** [comment]
Already changed that line on my Mac system but not yet on Git.
We still are unable to compile due to that Cubehash error.

Using Mavericks, boost 1.55.0 (patched), db48, xcode 5.1 and brew.

**Comment by MystPhysX** [comment]
I did not come across any other error during compilation on my machine. Can I get the full error message?

I used 10.6.8, boost 1.57 and db48. I generally stay away from any of the newer OSX versions as Clang is annoying with errors.

**Comment by equiteam** [comment]
Will adjust our VM to your specs and try to compile again.

**Comment by MystPhysX** [comment]
Okay let me know how it goes. This is the makefile I used to successfully compile on my machine: http://hastebin.com/bapuhilosu.avrasm

**Pull request merged**
